### ISSUE TITLE
Unable to sign in with Google

### ISSUE THREAD

**Issue by aaronfay** [rrgeorge/EncounterLog#1]
Just attempted to sign into D&D Beyond using the app and the Google login, received this error:

![screenshot 2023-01-15 at 11 37 00](https://user-images.githubusercontent.com/1033941/212563303-8cd54547-7cae-46f3-bcf3-af8b6672c06c.png)

Release `EncounterLog-2.6.9-universal-mac`. Just wanted to report the issue 👋🏻

**Comment by rrgeorge** [comment]
Unfortunately this is a constant problem with Google. You can try pressing Try Again, closing the window and trying again, and or quitting and trying again.
Though it’s a lot easier to just link your account with a different login provider like twitch or apple by going to https://www.dndbeyond.com/account
Then using that to login.

**Comment by aaronfay** [comment]
Yeah, DnDBeyond is 500-ing trying to connect an Apple account too, not sure if there's a path forward here 😂.

**Comment by aaronfay** [comment]
Oh, just an update, refreshing (Cmd+R) on the "Couldn't sign you in" page let me enter my email and then asked for a password instead of showing an error 👍🏻 . Thanks for the tip

**Comment by rrgeorge** [comment]
You have to login to the web and link your apple account in your account settings. If you’re on the E+ discord, I can help you get things working.

**Comment by aaronfay** [comment]
I got it working, thanks 👍🏻
