### ISSUE TITLE
Export Campaign Characters not working

### ISSUE THREAD

**Issue by Altom85** [rrgeorge/EncounterLog#4]
When I export Campaign Characters, it does create a compendium file but it's only 1KB which I find odd. When I try to import this file into EncounterPlus, it says no relevant information found. It does the same thing when I export Encounters too but I don't really use that feature anyway.

I tried uninstalling EncounterLog and reinstalling the newest version, running as an admin, and making sure I'm logged in on EncounterLog under my D&D beyond account. 

I think the strangest thing is I've done this in the past without any issues at all.

**Comment by rrgeorge** [comment]
EncounterLog doesn’t actually do the character conversion, it forwards the request to my converter at https://play5e.online
Nonetheless, I did discover an issue with the online converter, which I have now resolved. Please try converting your characters again.
